### ISSUE TITLE
parasite-scanner crashes on raspberry pi os 11.4

### ISSUE THREAD

**Issue by SystemFuchs** [rbaron/parasite-scanner#3]
It seems that an actual bluez stack forces parasite-scanner to crash.

pi@raspberrypi:~/parasite-scanner$ ./parasite-scanner -config example_config.yaml
panic: unable to initialize the BLE stack: MapToStruct: Field not found: Roles

goroutine 6 [running]:
main.(*ParasiteScanner).Run(0x200e2b0)
        /home/pi/parasite-scanner/ble.go:95 +0x13c
created by main.main
        /home/pi/parasite-scanner/main.go:33 +0x194
pi@raspberrypi:~/parasite-scanner$ uname -a

Linux raspberrypi 5.15.56-v7+ #1575 SMP Fri Jul 22 20:28:11 BST 2022 armv7l GNU/Linux

pi@raspberrypi:~/parasite-scanner$ cat /etc/debian_version
11.4

pi@raspberrypi:~/parasite-scanner$ bluetoothctl --version
bluetoothctl: 5.55

**Comment by SystemFuchs** [comment]
Sorted it out. 

1. It seems to be the case that your customized go bluetooth 0.3.0 repo isn't compatible with bluez versions > 5.48 anymore
2. Downloaded the actual go bluetooth 0.5.0 release & added your customizations manually. After this the package will build & will run fine. I'm trying to check, if the range with a raspi is better compared to the ESP32 ESPHome version. Allthough I'm using antennas I'm having trouble getting the signal wenn the glashouse door & the garden door (triple glas window) are closed

![image](https://user-images.githubusercontent.com/3988026/188408043-384fabb2-8196-4abb-bf71-e4cfb5dc9476.png)


Could you merge your go bluetooth repo changes with the actual 0.5.0 version? Regarding Github an automic merge seems possible! 
![image](https://user-images.githubusercontent.com/3988026/188407981-1efbf939-2bc1-4a8b-be81-5ae2f9d3a88c.png)

Best regards & thx for you efforts.

**Comment by leon2225** [comment]
Hey folks, is there an update on this?
It seems like the same issue persists.

Thanks for your efforts so far!

**Comment by rbaron** [comment]
It's been a while (2 years!) since I last touched this project. I have since moved my b-parasites to ESPHome + [BTHome](https://bthome.io/) + HomeAssistant (see [docs](https://github.com/rbaron/b-parasite/blob/main/code/nrf-connect/samples/ble/README.md#advertising-packet-encoding)), which I think it's an easier, cheaper and more battle tested way of integrating them into Home Assistant.

If someone wants to bring this project to a better shape, here's what I would suggest:
1. Removing the dependency on [github.com/rbaron/bluetooth](https://github.com/rbaron/parasite-scanner/blob/2ecf2912a842cb297f7f06a5350b86d757370f17/go.mod#LL12C66-L12C66). This was a quick hack on top of github.com/tinygo-org/bluetooth to support parsing service data from b-parasite BLE advertisements. It's possible that the upstream project supports the feature and maintains it (I just checked: apparently [not](https://github.com/tinygo-org/bluetooth/blob/e79ea1e4e99c2628e7219de0bd88da59adaf3d60/adapter_darwin.go#L123)), which is favorable over my hacky, untested, stale fork. If not, ideally fix the fork and try to contribute it upstream
2. Support newer [b-parasite BLE encodings](https://github.com/rbaron/b-parasite/blob/main/code/nrf-connect/samples/ble/README.md#advertising-packet-encoding). I build this when we only had V1, now we have V2 (which supports the light sensor) and also BTHome. Ideally this project should automatically parse all of them (and display which one they're using). [Here's where](https://github.com/rbaron/b-parasite/blob/117b257336c33b8caccccbeeefcdb0808954b3a9/code/nrf-connect/samples/ble/src/encoding.c#L8) data is encoded for all protocol versions
